version: '3.2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nuitdelinfo

  api:
    image: nouvelle0epoch/lne-user
    entrypoint:
      - /app/lne-user
      - start
      - --pg-hostname=postgres

    ports:
      - 8080:9900

    depends_on:
      - postgres

    links:
      - postgres:postgres